### ISSUE TITLE
RTF support?

### ISSUE THREAD

**Issue by homolibere** [jsFile/jsFile#1]
Hi, quite integesting project.
Are you planing to add RTF support and how soon?

**Comment by webschik** [comment]
Hi! I have plans to add support for formats:
- Rtf,
- Doc,
- Pdf,
- Pptx,
- Xlsx

Watch for updates ;)

**Comment by homolibere** [comment]
great! tnx!

**Comment by vitrum** [comment]
Looks cool!

**Comment by webschik** [comment]
Hi!
I've added support for RTF, but now there are problems with tables and images. But in any case already be used as text output correctly (established relevant issues)

**Comment by homolibere** [comment]
Great news, but... is it working at all?
When i tryed to open file in test.html (rtf file created by LibreOffice 4.1.2.3) JDOC trows an exception:
Object {message: "Invalid file type"} 

Test RTF File has no tables or images https://app.box.com/s/biiiww4d3io8xq7qtroa

**Comment by webschik** [comment]
Hi!
Perhaps you have an old version of the file test.html and it contains the 0.1.0 version of the library, while the current version is 0.2.0. Try to download the files from the Git branch 'master' again.

**Comment by homolibere** [comment]
nope, i'we pulled all changes from 'master' branch just now. 
In test.html JDOC set to ver. 0.2.0
script src="src/build/jdoc.0.2.0.js"
and it's still not working in chrome and firefox (bouth latest versions) and IE10
maybe i need somme dependencies or else?

**Comment by webschik** [comment]
very strange. I opened this file correctly. (FF 25, Chrome 30.0.1599.114, Ubuntu 13.04 and Win7). Maybe your browser cache for static pages?
