### ISSUE TITLE
Error - jf.read();

### ISSUE THREAD

**Issue by akburko** [jsFile/jsFile#19]
Console.log:
jsfile.js:1682 Uncaught (in promise) Event {isTrusted: true, type: "error", target: Worker, currentTarget: Worker, eventPhase: 0…}
##

**Comment by sferoze** [comment]
I seem to be getting the same issue when trying to read a word document..

specific message is
`"Uncaught SyntaxError: Unexpected token <"`

**Comment by webschik** [comment]
Hi guys,

If you are still interested in this issue, please check a project https://github.com/file2html/file2html. It has totally new engines for files reading, I've tried to solve there the most important problems from jsFile.
