### ISSUE TITLE
Невозможно открыть файл

### ISSUE THREAD

**Issue by eden-lane** [jsFile/jsFile#5]
При попытке открыть любой файл в test.html возникает ошибка:  

```
Uncaught NotReadableError: Failed to execute 'readAsText' on 'FileReaderSync': 
The requested file could not be read, typically due to permission problems that 
have occurred after a reference to a file was acquired. 
```

**Comment by webschik** [comment]
Подскажи какая ОС, браузер (его версия)?

**Comment by eden-lane** [comment]
Да, извиняюсь, что забыл указать.
Win7 x32, Chrome 33.0.1750.117 m.
Пробовал открывать `docx`, `doc` и `rtf`

**Comment by webschik** [comment]
Спасибо, баг подтверждаю, буду исправлять - ждите скорого обновления.
Пока советую решение:
1. Попробуйте закрыть все другие приложения, которые используют данный файл
2. В FF баг не обнаружился :)

**Comment by eden-lane** [comment]
Спасибо !
Подтверждаю: в Firefox открывается. Для других браузеров закрытие
приложений не помогает.

27 февраля 2014 г., 14:21 пользователь webschik
notifications@github.comнаписал:

**Comment by webschik** [comment]
Данный баг возникает в Google Chrome при открытии файла с локальной машины.
Т.е. если запустить test.html с любого веб-сервера и потом уже попытаться открыть текстовый файл, тогда бага уже не будет.

Также можно попытаться просто запустить Chrome с флагами, отключающими блокирование доступа к локальным файлам.
