### ISSUE TITLE
docx with images fails to open

### ISSUE THREAD

**Issue by 0xMarK** [jsFile/jsFile#7]
I have set up a test page of jDoc
https://dl.dropboxusercontent.com/u/1785510/Sites/jDoc-master/tests/test.html

But I get an error on line 11541 in file jdoc.0.5.0.js

```
data: this._normalizeDataURI(result, filename)
```

Me test docx-file is:
https://dl.dropboxusercontent.com/u/1785510/Sites/jDoc-master/tests/qs.docx

**Comment by webschik** [comment]
Thanks for your feedback. I will check it.

**Comment by webschik** [comment]
This bug fixed! 
But I found another https://github.com/webschik/jDoc/issues/8
I'm going to fix it at this week
